spring.application.name=THIGK2
spring.datasource.url=jdbc:mysql://localhost:3306/web2_giuaky?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true