spring.application.name=MiniProduct
# 1. Cấu hình kết nối MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=

# 2. Cấu hình Hibernate (Người phiên dịch tự động tạo bảng)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update